name: release

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: [self-hosted, micro-linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: avular-gpio

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install -y build-essential debhelper dh-python python3-all python3-all-dev python3-setuptools devscripts

      - name: Create Debian source package
        run: |
            cd avular-gpio
            VERSION=$(dpkg-parsechangelog --show-field Version | sed 's/-[^-]*$//')
            cd ..
            echo "Creating source package with version: $VERSION"
            tar -czvf avular-gpio_${VERSION}.orig.tar.gz --exclude-vcs --exclude=avular-gpio/debian avular-gpio/

      - name: Build package
        run: |
          ls -l
          echo "Building package..."
          cd avular-gpio
          debuild -us -uc

      - name: Create artifacts
        uses: actions/upload-artifact@v4
        with:
          name: avular-gpio-packages
          path: |
            *.deb

  release-stable:
    needs: build
    uses: avular-robotics/avular_ci/.github/workflows/upload-packages.yml@latest
    secrets: inherit
    strategy:
      matrix:
        environment: [stable, nightly, unstable]
    with:
      artifact-name: avular-gpio-packages
      environment: ${{ matrix.environment }}
